# Generated by Django 3.2.4 on 2022-09-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_mcart_morder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='ppic',
            new_name='pic',
        ),
    ]
